# tests/services/test_pdf_service.py
"""
Unit tests for PDF generation service.
Tests PDF creation and content validation.
"""

from decimal import Decimal
from io import BytesIO

import pytest
from PyPDF2 import PdfReader

from app.schemas.report_card_schema import ExamSummary, ReportCard, SubjectMark
from app.services.pdf_service import create_report_card_pdf


@pytest.fixture
def sample_report_card() -> ReportCard:
    """Provides a sample report card for testing."""
    return ReportCard(
        student_id=32,
        student_user_id="6ca19ec3-9f43-41a2-bef4-fc46f8a9b7b4",
        student_name="Myra Mishra",
        class_name="Grade 3 - B",
        exam_summaries=[
            ExamSummary(
                exam_name="March Final exams",
                marks=[SubjectMark(subject_name="Mathematics", marks_obtained=Decimal("92.00"), max_marks=Decimal("100.00")), SubjectMark(subject_name="Science", marks_obtained=Decimal("88.00"), max_marks=Decimal("100.00"))],
                total_obtained=Decimal("180.00"),
                total_max_marks=Decimal("200.00"),
                percentage=90.0,
            ),
            ExamSummary(exam_name="Surprise exams", marks=[SubjectMark(subject_name="Mathematics", marks_obtained=Decimal("95.00"), max_marks=Decimal("100.00"))], total_obtained=Decimal("95.00"), total_max_marks=Decimal("100.00"), percentage=95.0),
        ],
        grand_total_obtained=Decimal("275.00"),
        grand_total_max_marks=Decimal("300.00"),
        overall_percentage=91.67,
    )


@pytest.fixture
def minimal_report_card() -> ReportCard:
    """Provides a minimal report card with one exam and one subject."""
    return ReportCard(
        student_id=1,
        student_user_id="00000000-0000-0000-0000-000000000001",
        student_name="Test Student",
        class_name="Grade 1 - A",
        exam_summaries=[
            ExamSummary(exam_name="Test Exam", marks=[SubjectMark(subject_name="Test Subject", marks_obtained=Decimal("50.00"), max_marks=Decimal("100.00"))], total_obtained=Decimal("50.00"), total_max_marks=Decimal("100.00"), percentage=50.0)
        ],
        grand_total_obtained=Decimal("50.00"),
        grand_total_max_marks=Decimal("100.00"),
        overall_percentage=50.0,
    )


@pytest.mark.asyncio
class TestPDFServiceBasics:
    """Test basic PDF generation functionality."""

    async def test_create_pdf_returns_bytes(self, sample_report_card):
        """Test that PDF generation returns bytes."""
        pdf_bytes = await create_report_card_pdf(sample_report_card)

        assert pdf_bytes is not None
        assert isinstance(pdf_bytes, bytes)
        assert len(pdf_bytes) > 0

    async def test_pdf_has_reasonable_size(self, sample_report_card):
        """Test that generated PDF has a reasonable file size."""
        pdf_bytes = await create_report_card_pdf(sample_report_card)

        # PDF should be between 1KB and 1MB for a report card
        assert 1000 < len(pdf_bytes) < 1_000_000

    async def test_pdf_is_valid_format(self, sample_report_card):
        """Test that generated bytes form a valid PDF."""
        pdf_bytes = await create_report_card_pdf(sample_report_card)

        # PDF files start with %PDF
        assert pdf_bytes.startswith(b"%PDF")

    async def test_pdf_can_be_read_by_pypdf2(self, sample_report_card):
        """Test that generated PDF can be parsed by PyPDF2."""
        pdf_bytes = await create_report_card_pdf(sample_report_card)

        pdf_file = BytesIO(pdf_bytes)
        reader = PdfReader(pdf_file)

        # Should have at least one page
        assert len(reader.pages) >= 1

    async def test_minimal_report_card_generates_pdf(self, minimal_report_card):
        """Test PDF generation with minimal data."""
        pdf_bytes = await create_report_card_pdf(minimal_report_card)

        assert pdf_bytes is not None
        assert isinstance(pdf_bytes, bytes)
        assert len(pdf_bytes) > 0


@pytest.mark.asyncio
class TestPDFContentValidation:
    """Test that PDF contains correct content."""

    async def test_pdf_contains_student_name(self, sample_report_card):
        """Test that PDF contains the student's name."""
        pdf_bytes = await create_report_card_pdf(sample_report_card)

        pdf_file = BytesIO(pdf_bytes)
        reader = PdfReader(pdf_file)

        # Extract text from first page
        text = reader.pages[0].extract_text()

        assert "Myra Mishra" in text

    async def test_pdf_contains_class_name(self, sample_report_card):
        """Test that PDF contains the class information."""
        pdf_bytes = await create_report_card_pdf(sample_report_card)

        pdf_file = BytesIO(pdf_bytes)
        reader = PdfReader(pdf_file)
        text = reader.pages[0].extract_text()

        assert "Grade 3 - B" in text

    async def test_pdf_contains_report_card_title(self, sample_report_card):
        """Test that PDF contains the 'Report Card' title."""
        pdf_bytes = await create_report_card_pdf(sample_report_card)

        pdf_file = BytesIO(pdf_bytes)
        reader = PdfReader(pdf_file)
        text = reader.pages[0].extract_text()

        assert "Report Card" in text

    async def test_pdf_contains_exam_names(self, sample_report_card):
        """Test that PDF contains all exam names."""
        pdf_bytes = await create_report_card_pdf(sample_report_card)

        pdf_file = BytesIO(pdf_bytes)
        reader = PdfReader(pdf_file)
        text = reader.pages[0].extract_text()

        assert "March Final exams" in text
        assert "Surprise exams" in text

    async def test_pdf_contains_subject_names(self, sample_report_card):
        """Test that PDF contains subject names."""
        pdf_bytes = await create_report_card_pdf(sample_report_card)

        pdf_file = BytesIO(pdf_bytes)
        reader = PdfReader(pdf_file)
        text = reader.pages[0].extract_text()

        assert "Mathematics" in text
        assert "Science" in text

    async def test_pdf_contains_marks(self, sample_report_card):
        """Test that PDF contains marks data."""
        pdf_bytes = await create_report_card_pdf(sample_report_card)

        pdf_file = BytesIO(pdf_bytes)
        reader = PdfReader(pdf_file)
        text = reader.pages[0].extract_text()

        # Check for marks (as strings in PDF)
        assert "92" in text or "92.00" in text
        assert "100" in text or "100.00" in text

    async def test_pdf_contains_grand_totals(self, sample_report_card):
        """Test that PDF contains grand total information."""
        pdf_bytes = await create_report_card_pdf(sample_report_card)

        pdf_file = BytesIO(pdf_bytes)
        reader = PdfReader(pdf_file)
        text = reader.pages[0].extract_text()

        assert "275" in text  # Grand total obtained
        assert "300" in text  # Grand total max marks

    async def test_pdf_contains_overall_percentage(self, sample_report_card):
        """Test that PDF contains overall percentage."""
        pdf_bytes = await create_report_card_pdf(sample_report_card)

        pdf_file = BytesIO(pdf_bytes)
        reader = PdfReader(pdf_file)
        text = reader.pages[0].extract_text()

        # Should contain percentage with % symbol
        assert "91.67%" in text or "91.67" in text

    async def test_pdf_contains_overall_summary_section(self, sample_report_card):
        """Test that PDF has an 'Overall Summary' section."""
        pdf_bytes = await create_report_card_pdf(sample_report_card)

        pdf_file = BytesIO(pdf_bytes)
        reader = PdfReader(pdf_file)
        text = reader.pages[0].extract_text()

        assert "Overall Summary" in text


@pytest.mark.asyncio
class TestPDFWithEdgeCases:
    """Test PDF generation with edge cases."""

    async def test_pdf_with_none_percentage(self):
        """Test PDF generation when percentage is None (division by zero case)."""
        report_card = ReportCard(
            student_id=1,
            student_user_id="00000000-0000-0000-0000-000000000002",
            student_name="Test Student",
            class_name="Grade 1 - A",
            exam_summaries=[
                ExamSummary(exam_name="Test Exam", marks=[SubjectMark(subject_name="Test", marks_obtained=Decimal("0"), max_marks=Decimal("0"))], total_obtained=Decimal("0"), total_max_marks=Decimal("0"), percentage=None)  # This is the edge case
            ],
            grand_total_obtained=Decimal("0"),
            grand_total_max_marks=Decimal("0"),
            overall_percentage=None,
        )

        # Should not raise an exception
        pdf_bytes = await create_report_card_pdf(report_card)

        assert pdf_bytes is not None
        assert len(pdf_bytes) > 0

        # Verify PDF contains N/A for percentage
        pdf_file = BytesIO(pdf_bytes)
        reader = PdfReader(pdf_file)
        text = reader.pages[0].extract_text()

        assert "N/A" in text

    async def test_pdf_with_long_names(self):
        """Test PDF generation with very long names."""
        report_card = ReportCard(
            student_id=1,
            student_user_id="00000000-0000-0000-0000-000000000003",
            student_name="A" * 100,  # Very long name
            class_name="Grade 12 - SuperLongSectionName",
            exam_summaries=[
                ExamSummary(
                    exam_name="Very Long Exam Name That Goes On And On",
                    marks=[SubjectMark(subject_name="Long Subject Name", marks_obtained=Decimal("50"), max_marks=Decimal("100"))],
                    total_obtained=Decimal("50"),
                    total_max_marks=Decimal("100"),
                    percentage=50.0,
                )
            ],
            grand_total_obtained=Decimal("50"),
            grand_total_max_marks=Decimal("100"),
            overall_percentage=50.0,
        )

        # Should not raise an exception
        pdf_bytes = await create_report_card_pdf(report_card)
        assert pdf_bytes is not None

    async def test_pdf_with_many_exams(self):
        """Test PDF generation with many exams."""
        # Create 10 exams
        exam_summaries = []
        for i in range(10):
            exam_summaries.append(
                ExamSummary(
                    exam_name=f"Exam {i+1}",
                    marks=[SubjectMark(subject_name=f"Subject {j+1}", marks_obtained=Decimal("80"), max_marks=Decimal("100")) for j in range(3)],  # 3 subjects per exam
                    total_obtained=Decimal("240"),
                    total_max_marks=Decimal("300"),
                    percentage=80.0,
                )
            )

        report_card = ReportCard(
            student_id=1,
            student_user_id="00000000-0000-0000-0000-000000000004",
            student_name="Test Student",
            class_name="Grade 10 - A",
            exam_summaries=exam_summaries,
            grand_total_obtained=Decimal("2400"),
            grand_total_max_marks=Decimal("3000"),
            overall_percentage=80.0,
        )

        pdf_bytes = await create_report_card_pdf(report_card)

        assert pdf_bytes is not None
        # PDF might be multiple pages for many exams
        pdf_file = BytesIO(pdf_bytes)
        reader = PdfReader(pdf_file)
        assert len(reader.pages) >= 1

    async def test_pdf_with_decimal_marks(self):
        """Test PDF generation with fractional marks."""
        report_card = ReportCard(
            student_id=1,
            student_user_id="00000000-0000-0000-0000-000000000005",
            student_name="Test Student",
            class_name="Grade 5 - B",
            exam_summaries=[ExamSummary(exam_name="Test Exam", marks=[SubjectMark(subject_name="Math", marks_obtained=Decimal("87.5"), max_marks=Decimal("100.0"))], total_obtained=Decimal("87.5"), total_max_marks=Decimal("100.0"), percentage=87.5)],
            grand_total_obtained=Decimal("87.5"),
            grand_total_max_marks=Decimal("100.0"),
            overall_percentage=87.5,
        )

        pdf_bytes = await create_report_card_pdf(report_card)

        assert pdf_bytes is not None

        pdf_file = BytesIO(pdf_bytes)
        reader = PdfReader(pdf_file)
        text = reader.pages[0].extract_text()

        # Should contain the decimal marks
        assert "87.5" in text or "87.50" in text


@pytest.mark.asyncio
class TestPDFServicePerformance:
    """Test performance aspects of PDF generation."""

    async def test_pdf_generation_is_fast(self, sample_report_card):
        """Test that PDF generation completes in reasonable time."""
        import time

        start = time.time()
        pdf_bytes = await create_report_card_pdf(sample_report_card)
        end = time.time()

        # Should complete in less than 2 seconds
        assert (end - start) < 2.0
        assert pdf_bytes is not None

    async def test_multiple_pdf_generations(self, sample_report_card):
        """Test that multiple PDFs can be generated without issues."""
        for _ in range(5):
            pdf_bytes = await create_report_card_pdf(sample_report_card)
            assert pdf_bytes is not None
            assert len(pdf_bytes) > 0
