// ============================================================================
// MOCK STAFF DATA PROVIDER
// ============================================================================

import type {
  Staff,
  StaffCreate,
  StaffUpdate,
} from "../services/hr.schema";

export const MOCK_STAFF: Staff[] = [
  {
    staff_id: 1,
    school_id: 1,
    employee_id: "EMP001",
    first_name: "Rajesh",
    last_name: "Kumar",
    full_name: "Rajesh Kumar",
    email: "rajesh.kumar@school.com",
    phone: "+91-9876543210",
    gender: "Male",
    department_id: 1,
    designation: "Principal",
    role: "Management",
    joining_date: "2018-01-15",
    employment_status: "Active",
    qualification: "M.A. in Education",
    experience_years: 12,
    professional_qualification: "Ph.D. in Educational Leadership",
    certifications: ["ISO 9001:2015", "CBSE Certification"],
    address: "123 School Street",
    city: "Delhi",
    state: "Delhi",
    pincode: "110001",
    emergency_contact_name: "Priya Kumar",
    emergency_contact_phone: "+91-9876543211",
    emergency_contact_relation: "Spouse",
    bank_name: "HDFC Bank",
    account_number: "1234567890",
    ifsc_code: "HDFC0001234",
    pan: "ABCDE1234F",
    is_active: true,
    periods_per_week: 8,
    profile_photo_url: "https://placehold.co/200/2563eb/white?text=RK",
    created_at: "2018-01-15T00:00:00Z",
  },
  {
    staff_id: 2,
    school_id: 1,
    employee_id: "EMP002",
    first_name: "Priya",
    last_name: "Sharma",
    full_name: "Priya Sharma",
    email: "priya.sharma@school.com",
    phone: "+91-9876543212",
    gender: "Female",
    department_id: 2,
    designation: "Mathematics HOD",
    role: "Teaching",
    joining_date: "2019-07-01",
    employment_status: "Active",
    qualification: "M.Sc. in Mathematics",
    subjects: ["Mathematics", "Statistics"],
    experience_years: 8,
    professional_qualification: "B.Ed.",
    certifications: ["IGCSE Mathematics", "Advanced Mathematics"],
    address: "456 Teacher Lane",
    city: "Delhi",
    state: "Delhi",
    pincode: "110002",
    emergency_contact_name: "Amit Sharma",
    emergency_contact_phone: "+91-9876543213",
    emergency_contact_relation: "Brother",
    bank_name: "ICICI Bank",
    account_number: "9876543210",
    ifsc_code: "ICIC0001234",
    pan: "FGHIJ5678K",
    is_active: true,
    periods_per_week: 28,
    profile_photo_url: "https://placehold.co/200/10b981/white?text=PS",
    created_at: "2019-07-01T00:00:00Z",
  },
  {
    staff_id: 3,
    school_id: 1,
    employee_id: "EMP003",
    first_name: "Anjali",
    last_name: "Patel",
    full_name: "Anjali Patel",
    email: "anjali.patel@school.com",
    phone: "+91-9876543214",
    gender: "Female",
    department_id: 2,
    designation: "Mathematics Teacher",
    role: "Teaching",
    joining_date: "2020-06-15",
    employment_status: "Active",
    qualification: "M.Sc. in Mathematics",
    subjects: ["Mathematics", "Applied Mathematics"],
    experience_years: 5,
    professional_qualification: "B.Ed.",
    certifications: ["CBSE Mathematics"],
    address: "789 School Colony",
    city: "Gurgaon",
    state: "Haryana",
    pincode: "122001",
    emergency_contact_name: "Vikram Patel",
    emergency_contact_phone: "+91-9876543215",
    emergency_contact_relation: "Father",
    bank_name: "AXIS Bank",
    account_number: "5555555555",
    ifsc_code: "AXIS0001234",
    pan: "LMNOP9101Q",
    is_active: true,
    periods_per_week: 32,
    profile_photo_url: "https://placehold.co/200/f59e0b/white?text=AP",
    created_at: "2020-06-15T00:00:00Z",
  },
  {
    staff_id: 4,
    school_id: 1,
    employee_id: "EMP004",
    first_name: "Vikram",
    last_name: "Singh",
    full_name: "Vikram Singh",
    email: "vikram.singh@school.com",
    phone: "+91-9876543216",
    gender: "Male",
    department_id: 3,
    designation: "Science HOD",
    role: "Teaching",
    joining_date: "2019-04-10",
    employment_status: "Active",
    qualification: "M.Sc. in Physics",
    subjects: ["Physics", "Chemistry", "Science"],
    experience_years: 9,
    professional_qualification: "B.Ed.",
    certifications: ["IGCSE Science"],
    address: "101 Academic Street",
    city: "Delhi",
    state: "Delhi",
    pincode: "110003",
    emergency_contact_name: "Neha Singh",
    emergency_contact_phone: "+91-9876543217",
    emergency_contact_relation: "Spouse",
    bank_name: "HDFC Bank",
    account_number: "1111111111",
    ifsc_code: "HDFC0002345",
    pan: "RSTUV2345W",
    is_active: true,
    periods_per_week: 26,
    profile_photo_url: "https://placehold.co/200/ef4444/white?text=VS",
    created_at: "2019-04-10T00:00:00Z",
  },
  {
    staff_id: 5,
    school_id: 1,
    employee_id: "EMP005",
    first_name: "Deepa",
    last_name: "Verma",
    full_name: "Deepa Verma",
    email: "deepa.verma@school.com",
    phone: "+91-9876543218",
    gender: "Female",
    department_id: 4,
    designation: "IT HOD",
    role: "Teaching",
    joining_date: "2021-01-20",
    employment_status: "Active",
    qualification: "B.Tech in IT",
    subjects: ["Computer Science", "Information Technology"],
    experience_years: 6,
    professional_qualification: "M.Tech",
    certifications: ["AWS Solutions Architect", "Google Cloud"],
    address: "202 Tech Park",
    city: "Gurgaon",
    state: "Haryana",
    pincode: "122002",
    emergency_contact_name: "Sanjay Verma",
    emergency_contact_phone: "+91-9876543219",
    emergency_contact_relation: "Father",
    bank_name: "ICICI Bank",
    account_number: "2222222222",
    ifsc_code: "ICIC0002345",
    pan: "XYZA1234BC",
    is_active: true,
    periods_per_week: 24,
    profile_photo_url: "https://placehold.co/200/8b5cf6/white?text=DV",
    created_at: "2021-01-20T00:00:00Z",
  },
  {
    staff_id: 6,
    school_id: 1,
    employee_id: "EMP006",
    first_name: "Arjun",
    last_name: "Nair",
    full_name: "Arjun Nair",
    email: "arjun.nair@school.com",
    phone: "+91-9876543220",
    gender: "Male",
    department_id: 5,
    designation: "Office Coordinator",
    role: "Support",
    joining_date: "2021-03-01",
    employment_status: "Active",
    qualification: "Bachelor of Commerce",
    experience_years: 2,
    professional_qualification: undefined,
    certifications: [],
    address: "303 School Support",
    city: "Delhi",
    state: "Delhi",
    pincode: "110004",
    emergency_contact_name: "Kavya Nair",
    emergency_contact_phone: "+91-9876543221",
    emergency_contact_relation: "Sister",
    bank_name: "HDFC Bank",
    account_number: "3333333333",
    ifsc_code: "HDFC0003456",
    pan: "DEFG5678HI",
    is_active: true,
    periods_per_week: 0,
    profile_photo_url: "https://placehold.co/200/06b6d4/white?text=AN",
    created_at: "2021-03-01T00:00:00Z",
  },
  {
    staff_id: 7,
    school_id: 1,
    employee_id: "EMP007",
    first_name: "Meera",
    last_name: "Desai",
    full_name: "Meera Desai",
    email: "meera.desai@school.com",
    phone: "+91-9876543222",
    gender: "Female",
    department_id: 1,
    designation: "Academic Coordinator",
    role: "Administration",
    joining_date: "2020-08-15",
    employment_status: "On Leave",
    qualification: "Master of Education",
    experience_years: 6,
    professional_qualification: "B.Ed.",
    certifications: ["Curriculum Design"],
    address: "404 Academic Block",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560001",
    emergency_contact_name: "Rohan Desai",
    emergency_contact_phone: "+91-9876543223",
    emergency_contact_relation: "Spouse",
    bank_name: "AXIS Bank",
    account_number: "4444444444",
    ifsc_code: "AXIS0002345",
    pan: "IJKL9101MN",
    is_active: true,
    periods_per_week: 12,
    profile_photo_url: "https://placehold.co/200/ec4899/white?text=MD",
    created_at: "2020-08-15T00:00:00Z",
  },
  {
    staff_id: 8,
    school_id: 1,
    employee_id: "EMP008",
    first_name: "Nikhil",
    last_name: "Chopra",
    full_name: "Nikhil Chopra",
    email: "nikhil.chopra@school.com",
    phone: "+91-9876543224",
    gender: "Male",
    department_id: 4,
    designation: "Lab Technician",
    role: "Non-Teaching",
    joining_date: "2021-06-01",
    employment_status: "Active",
    qualification: "Diploma in Science",
    experience_years: 1,
    professional_qualification: undefined,
    certifications: ["Lab Safety"],
    address: "505 Lab Street",
    city: "Delhi",
    state: "Delhi",
    pincode: "110005",
    emergency_contact_name: "Shruti Chopra",
    emergency_contact_phone: "+91-9876543225",
    emergency_contact_relation: "Sister",
    bank_name: "ICICI Bank",
    account_number: "5555555556",
    ifsc_code: "ICIC0003456",
    pan: "OPQR2345ST",
    is_active: true,
    periods_per_week: 0,
    profile_photo_url: "https://placehold.co/200/14b8a6/white?text=NC",
    created_at: "2021-06-01T00:00:00Z",
  },
  {
    staff_id: 9,
    school_id: 1,
    employee_id: "EMP009",
    first_name: "Kavitha",
    last_name: "Rao",
    full_name: "Kavitha Rao",
    email: "kavitha.rao@school.com",
    phone: "+91-9876543226",
    gender: "Female",
    department_id: 6,
    designation: "English HOD",
    role: "Teaching",
    joining_date: "2018-06-01",
    employment_status: "Active",
    qualification: "M.A. in English Literature",
    subjects: ["English", "Literature", "Grammar"],
    experience_years: 10,
    professional_qualification: "B.Ed.",
    certifications: ["Cambridge English", "IELTS Trainer"],
    address: "606 Language Block",
    city: "Delhi",
    state: "Delhi",
    pincode: "110006",
    emergency_contact_name: "Ramesh Rao",
    emergency_contact_phone: "+91-9876543227",
    emergency_contact_relation: "Spouse",
    bank_name: "SBI",
    account_number: "6666666666",
    ifsc_code: "SBIN0001234",
    pan: "UVWX3456YZ",
    is_active: true,
    periods_per_week: 30,
    profile_photo_url: "https://placehold.co/200/f97316/white?text=KR",
    created_at: "2018-06-01T00:00:00Z",
  },
  {
    staff_id: 10,
    school_id: 1,
    employee_id: "EMP010",
    first_name: "Suresh",
    last_name: "Menon",
    full_name: "Suresh Menon",
    email: "suresh.menon@school.com",
    phone: "+91-9876543228",
    gender: "Male",
    department_id: 3,
    designation: "Chemistry Teacher",
    role: "Teaching",
    joining_date: "2019-08-15",
    employment_status: "Active",
    qualification: "M.Sc. in Chemistry",
    subjects: ["Chemistry", "Science"],
    experience_years: 7,
    professional_qualification: "B.Ed.",
    certifications: ["CBSE Chemistry"],
    address: "707 Science Block",
    city: "Delhi",
    state: "Delhi",
    pincode: "110007",
    emergency_contact_name: "Lakshmi Menon",
    emergency_contact_phone: "+91-9876543229",
    emergency_contact_relation: "Mother",
    bank_name: "HDFC Bank",
    account_number: "7777777777",
    ifsc_code: "HDFC0004567",
    pan: "ABCD5678EF",
    is_active: true,
    periods_per_week: 34,
    profile_photo_url: "https://placehold.co/200/84cc16/white?text=SM",
    created_at: "2019-08-15T00:00:00Z",
  },
  {
    staff_id: 11,
    school_id: 1,
    employee_id: "EMP011",
    first_name: "Pooja",
    last_name: "Agarwal",
    full_name: "Pooja Agarwal",
    email: "pooja.agarwal@school.com",
    phone: "+91-9876543230",
    gender: "Female",
    department_id: 2,
    designation: "Mathematics Teacher",
    role: "Teaching",
    joining_date: "2022-01-10",
    employment_status: "Active",
    qualification: "M.Sc. in Mathematics",
    subjects: ["Mathematics"],
    experience_years: 3,
    professional_qualification: "B.Ed.",
    certifications: [],
    address: "808 Math Block",
    city: "Noida",
    state: "Uttar Pradesh",
    pincode: "201301",
    emergency_contact_name: "Rajesh Agarwal",
    emergency_contact_phone: "+91-9876543231",
    emergency_contact_relation: "Father",
    bank_name: "ICICI Bank",
    account_number: "8888888888",
    ifsc_code: "ICIC0004567",
    pan: "GHIJ6789KL",
    is_active: true,
    periods_per_week: 28,
    profile_photo_url: "https://placehold.co/200/a855f7/white?text=PA",
    created_at: "2022-01-10T00:00:00Z",
  },
  {
    staff_id: 12,
    school_id: 1,
    employee_id: "EMP012",
    first_name: "Rahul",
    last_name: "Gupta",
    full_name: "Rahul Gupta",
    email: "rahul.gupta@school.com",
    phone: "+91-9876543232",
    gender: "Male",
    department_id: 6,
    designation: "Hindi Teacher",
    role: "Teaching",
    joining_date: "2020-03-15",
    employment_status: "Active",
    qualification: "M.A. in Hindi",
    subjects: ["Hindi", "Sanskrit"],
    experience_years: 5,
    professional_qualification: "B.Ed.",
    certifications: ["Hindi Sahitya"],
    address: "909 Language Block",
    city: "Delhi",
    state: "Delhi",
    pincode: "110008",
    emergency_contact_name: "Sunita Gupta",
    emergency_contact_phone: "+91-9876543233",
    emergency_contact_relation: "Spouse",
    bank_name: "SBI",
    account_number: "9999999999",
    ifsc_code: "SBIN0002345",
    pan: "MNOP7890QR",
    is_active: true,
    periods_per_week: 26,
    profile_photo_url: "https://placehold.co/200/22c55e/white?text=RG",
    created_at: "2020-03-15T00:00:00Z",
  },
  {
    staff_id: 13,
    school_id: 1,
    employee_id: "EMP013",
    first_name: "Sneha",
    last_name: "Joshi",
    full_name: "Sneha Joshi",
    email: "sneha.joshi@school.com",
    phone: "+91-9876543234",
    gender: "Female",
    department_id: 3,
    designation: "Biology Teacher",
    role: "Teaching",
    joining_date: "2021-07-01",
    employment_status: "Active",
    qualification: "M.Sc. in Biology",
    subjects: ["Biology", "Life Science"],
    experience_years: 4,
    professional_qualification: "B.Ed.",
    certifications: ["CBSE Biology"],
    address: "1010 Science Block",
    city: "Gurgaon",
    state: "Haryana",
    pincode: "122003",
    emergency_contact_name: "Anil Joshi",
    emergency_contact_phone: "+91-9876543235",
    emergency_contact_relation: "Father",
    bank_name: "AXIS Bank",
    account_number: "1010101010",
    ifsc_code: "AXIS0003456",
    pan: "STUV8901WX",
    is_active: true,
    periods_per_week: 30,
    profile_photo_url: "https://placehold.co/200/06b6d4/white?text=SJ",
    created_at: "2021-07-01T00:00:00Z",
  },
  {
    staff_id: 14,
    school_id: 1,
    employee_id: "EMP014",
    first_name: "Arun",
    last_name: "Krishnan",
    full_name: "Arun Krishnan",
    email: "arun.krishnan@school.com",
    phone: "+91-9876543236",
    gender: "Male",
    department_id: 4,
    designation: "Computer Teacher",
    role: "Teaching",
    joining_date: "2022-04-01",
    employment_status: "Active",
    qualification: "MCA",
    subjects: ["Computer Science", "Programming"],
    experience_years: 2,
    professional_qualification: "B.Ed.",
    certifications: ["Python Developer", "Web Development"],
    address: "1111 IT Block",
    city: "Delhi",
    state: "Delhi",
    pincode: "110009",
    emergency_contact_name: "Lakshmi Krishnan",
    emergency_contact_phone: "+91-9876543237",
    emergency_contact_relation: "Mother",
    bank_name: "HDFC Bank",
    account_number: "1111111112",
    ifsc_code: "HDFC0005678",
    pan: "YZAB9012CD",
    is_active: true,
    periods_per_week: 24,
    profile_photo_url: "https://placehold.co/200/3b82f6/white?text=AK",
    created_at: "2022-04-01T00:00:00Z",
  },
  {
    staff_id: 15,
    school_id: 1,
    employee_id: "EMP015",
    first_name: "Divya",
    last_name: "Nair",
    full_name: "Divya Nair",
    email: "divya.nair@school.com",
    phone: "+91-9876543238",
    gender: "Female",
    department_id: 5,
    designation: "HR Manager",
    role: "Administration",
    joining_date: "2019-09-01",
    employment_status: "Active",
    qualification: "MBA in HR",
    experience_years: 7,
    professional_qualification: "SHRM Certified",
    certifications: ["SHRM-CP", "HR Analytics"],
    address: "1212 Admin Block",
    city: "Delhi",
    state: "Delhi",
    pincode: "110010",
    emergency_contact_name: "Vijay Nair",
    emergency_contact_phone: "+91-9876543239",
    emergency_contact_relation: "Spouse",
    bank_name: "ICICI Bank",
    account_number: "1212121212",
    ifsc_code: "ICIC0005678",
    pan: "EFGH0123IJ",
    is_active: true,
    periods_per_week: 0,
    profile_photo_url: "https://placehold.co/200/f43f5e/white?text=DN",
    created_at: "2019-09-01T00:00:00Z",
  },
  {
    staff_id: 16,
    school_id: 1,
    employee_id: "EMP016",
    first_name: "Karthik",
    last_name: "Iyer",
    full_name: "Karthik Iyer",
    email: "karthik.iyer@school.com",
    phone: "+91-9876543240",
    gender: "Male",
    department_id: 3,
    designation: "Physics Teacher",
    role: "Teaching",
    joining_date: "2020-11-15",
    employment_status: "Active",
    qualification: "M.Sc. in Physics",
    subjects: ["Physics", "Mathematics"],
    experience_years: 6,
    professional_qualification: "B.Ed.",
    certifications: ["CBSE Physics", "Olympiad Coach"],
    address: "1313 Science Block",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600001",
    emergency_contact_name: "Padma Iyer",
    emergency_contact_phone: "+91-9876543241",
    emergency_contact_relation: "Mother",
    bank_name: "SBI",
    account_number: "1313131313",
    ifsc_code: "SBIN0003456",
    pan: "KLMN1234OP",
    is_active: true,
    periods_per_week: 32,
    profile_photo_url: "https://placehold.co/200/eab308/white?text=KI",
    created_at: "2020-11-15T00:00:00Z",
  },
  {
    staff_id: 17,
    school_id: 1,
    employee_id: "EMP017",
    first_name: "Lakshmi",
    last_name: "Reddy",
    full_name: "Lakshmi Reddy",
    email: "lakshmi.reddy@school.com",
    phone: "+91-9876543242",
    gender: "Female",
    department_id: 6,
    designation: "English Teacher",
    role: "Teaching",
    joining_date: "2021-08-01",
    employment_status: "Active",
    qualification: "M.A. in English",
    subjects: ["English", "Communicative English"],
    experience_years: 4,
    professional_qualification: "B.Ed.",
    certifications: ["TESOL"],
    address: "1414 Language Block",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500001",
    emergency_contact_name: "Venkat Reddy",
    emergency_contact_phone: "+91-9876543243",
    emergency_contact_relation: "Spouse",
    bank_name: "HDFC Bank",
    account_number: "1414141414",
    ifsc_code: "HDFC0006789",
    pan: "QRST2345UV",
    is_active: true,
    periods_per_week: 28,
    profile_photo_url: "https://placehold.co/200/ec4899/white?text=LR",
    created_at: "2021-08-01T00:00:00Z",
  },
  {
    staff_id: 18,
    school_id: 1,
    employee_id: "EMP018",
    first_name: "Sanjay",
    last_name: "Mehta",
    full_name: "Sanjay Mehta",
    email: "sanjay.mehta@school.com",
    phone: "+91-9876543244",
    gender: "Male",
    department_id: 1,
    designation: "Vice Principal",
    role: "Management",
    joining_date: "2017-03-01",
    employment_status: "Active",
    qualification: "M.Ed.",
    experience_years: 15,
    professional_qualification: "Ph.D. in Education",
    certifications: ["School Leadership"],
    address: "1515 Admin Block",
    city: "Delhi",
    state: "Delhi",
    pincode: "110011",
    emergency_contact_name: "Anita Mehta",
    emergency_contact_phone: "+91-9876543245",
    emergency_contact_relation: "Spouse",
    bank_name: "AXIS Bank",
    account_number: "1515151515",
    ifsc_code: "AXIS0004567",
    pan: "WXYZ3456AB",
    is_active: true,
    periods_per_week: 10,
    profile_photo_url: "https://placehold.co/200/6366f1/white?text=SM",
    created_at: "2017-03-01T00:00:00Z",
  },
  {
    staff_id: 19,
    school_id: 1,
    employee_id: "EMP019",
    first_name: "Rekha",
    last_name: "Bansal",
    full_name: "Rekha Bansal",
    email: "rekha.bansal@school.com",
    phone: "+91-9876543246",
    gender: "Female",
    department_id: 2,
    designation: "Mathematics Teacher",
    role: "Teaching",
    joining_date: "2023-01-15",
    employment_status: "Active",
    qualification: "M.Sc. in Mathematics",
    subjects: ["Mathematics", "Vedic Maths"],
    experience_years: 2,
    professional_qualification: "B.Ed.",
    certifications: [],
    address: "1616 Math Block",
    city: "Delhi",
    state: "Delhi",
    pincode: "110012",
    emergency_contact_name: "Sunil Bansal",
    emergency_contact_phone: "+91-9876543247",
    emergency_contact_relation: "Father",
    bank_name: "ICICI Bank",
    account_number: "1616161616",
    ifsc_code: "ICIC0006789",
    pan: "CDEF4567GH",
    is_active: true,
    periods_per_week: 30,
    profile_photo_url: "https://placehold.co/200/8b5cf6/white?text=RB",
    created_at: "2023-01-15T00:00:00Z",
  },
  {
    staff_id: 20,
    school_id: 1,
    employee_id: "EMP020",
    first_name: "Amit",
    last_name: "Saxena",
    full_name: "Amit Saxena",
    email: "amit.saxena@school.com",
    phone: "+91-9876543248",
    gender: "Male",
    department_id: 5,
    designation: "Accountant",
    role: "Administration",
    joining_date: "2018-05-01",
    employment_status: "Active",
    qualification: "B.Com, CA",
    experience_years: 8,
    professional_qualification: "Chartered Accountant",
    certifications: ["GST Practitioner"],
    address: "1717 Finance Block",
    city: "Delhi",
    state: "Delhi",
    pincode: "110013",
    emergency_contact_name: "Priya Saxena",
    emergency_contact_phone: "+91-9876543249",
    emergency_contact_relation: "Spouse",
    bank_name: "SBI",
    account_number: "1717171717",
    ifsc_code: "SBIN0004567",
    pan: "IJKL5678MN",
    is_active: true,
    periods_per_week: 0,
    profile_photo_url: "https://placehold.co/200/0ea5e9/white?text=AS",
    created_at: "2018-05-01T00:00:00Z",
  },
];

/**
 * Mock Staff Data Provider
 */
export const mockStaffProvider = {
  async getAll(): Promise<Staff[]> {
    return new Promise((resolve) => {
      setTimeout(() => resolve([...MOCK_STAFF]), 500);
    });
  },

  async getById(staffId: number): Promise<Staff | null> {
    return new Promise((resolve) => {
      setTimeout(() => {
        const staff = MOCK_STAFF.find((s) => s.staff_id === staffId);
        resolve(staff || null);
      }, 300);
    });
  },

  async getByDepartment(departmentId: number): Promise<Staff[]> {
    return new Promise((resolve) => {
      setTimeout(() => {
        const staff = MOCK_STAFF.filter((s) => s.department_id === departmentId);
        resolve(staff);
      }, 400);
    });
  },

  async create(payload: StaffCreate): Promise<Staff> {
    return new Promise((resolve) => {
      setTimeout(() => {
        const newStaff: Staff = {
          staff_id: Math.max(...MOCK_STAFF.map((s) => s.staff_id), 0) + 1,
          school_id: 1,
          full_name: `${payload.first_name} ${payload.last_name}`,
          is_active: payload.is_active ?? true,
          experience_years: 0,
          created_at: new Date().toISOString(),
          profile_photo_url: `https://placehold.co/200/2563eb/white?text=${payload.first_name.charAt(0)}${payload.last_name.charAt(0)}`,
          ...payload,
        };
        MOCK_STAFF.push(newStaff);
        resolve(newStaff);
      }, 400);
    });
  },

  async update(staffId: number, payload: StaffUpdate): Promise<Staff> {
    return new Promise((resolve) => {
      setTimeout(() => {
        const idx = MOCK_STAFF.findIndex((s) => s.staff_id === staffId);
        if (idx < 0) throw new Error("Staff not found");
        MOCK_STAFF[idx] = {
          ...MOCK_STAFF[idx],
          ...payload,
          updated_at: new Date().toISOString(),
        };
        resolve(MOCK_STAFF[idx]);
      }, 400);
    });
  },

  async delete(staffId: number): Promise<void> {
    return new Promise((resolve) => {
      setTimeout(() => {
        const idx = MOCK_STAFF.findIndex((s) => s.staff_id === staffId);
        if (idx >= 0) {
          MOCK_STAFF.splice(idx, 1);
        }
        resolve();
      }, 300);
    });
  },
};
