/**
 * ChatChart.tsx
 *
 * Renders inline chart visualizations in chat messages.
 * Displays base64-encoded PNG images generated by the backend graph_tool.
 *
 * Features:
 * - Responsive sizing that fits within message bubbles
 * - Loading skeleton while image loads
 * - Error handling with fallback
 * - Click to expand (optional modal view)
 * - Accessible with alt text
 */

import { useState, useCallback } from 'react';
import { ChartData } from '@/app/stores/useChatStore';

interface ChatChartProps {
  chart: ChartData;
  className?: string;
}

/**
 * Validates base64 image data
 */
function isValidBase64Image(data: string): boolean {
  if (!data || typeof data !== 'string') return false;
  // Check if it's a valid base64 string (basic check)
  try {
    // Remove data URL prefix if present
    const base64Only = data.replace(/^data:image\/\w+;base64,/, '');
    return base64Only.length > 0 && /^[A-Za-z0-9+/=]+$/.test(base64Only);
  } catch {
    return false;
  }
}

/**
 * Formats base64 data as a proper data URL
 */
function formatImageSrc(base64Data: string): string {
  // Already has data URL prefix
  if (base64Data.startsWith('data:image/')) {
    return base64Data;
  }
  // Add PNG data URL prefix (our backend generates PNGs)
  return `data:image/png;base64,${base64Data}`;
}

export default function ChatChart({ chart, className = '' }: ChatChartProps) {
  const [isLoading, setIsLoading] = useState(true);
  const [hasError, setHasError] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);

  const handleLoad = useCallback(() => {
    setIsLoading(false);
  }, []);

  const handleError = useCallback(() => {
    setIsLoading(false);
    setHasError(true);
  }, []);

  const toggleExpand = useCallback(() => {
    setIsExpanded((prev) => !prev);
  }, []);

  // Validate chart data
  if (!chart?.base64_image || !isValidBase64Image(chart.base64_image)) {
    return (
      <div className="chat-chart-error flex items-center gap-2 p-3 bg-gray-100 dark:bg-gray-700 rounded-lg text-sm text-gray-500 dark:text-gray-400">
        <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
        <span>Chart unavailable</span>
      </div>
    );
  }

  const imageSrc = formatImageSrc(chart.base64_image);
  const altText = chart.title || `${chart.chart_type || 'Analytics'} chart`;

  return (
    <>
      <div className={`chat-chart-container mt-3 ${className}`}>
        {/* Loading skeleton */}
        {isLoading && !hasError && (
          <div className="chat-chart-skeleton animate-pulse bg-gray-200 dark:bg-gray-700 rounded-lg w-full h-48 flex items-center justify-center">
            <svg className="w-8 h-8 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
            </svg>
          </div>
        )}

        {/* Error state */}
        {hasError && (
          <div className="chat-chart-error flex items-center gap-2 p-3 bg-red-50 dark:bg-red-900/20 rounded-lg text-sm text-red-600 dark:text-red-400">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span>Failed to load chart</span>
          </div>
        )}

        {/* Chart image */}
        <img
          src={imageSrc}
          alt={altText}
          title="Click to expand"
          className={`chat-chart cursor-pointer transition-transform hover:scale-[1.02] ${isLoading || hasError ? 'hidden' : ''}`}
          onLoad={handleLoad}
          onError={handleError}
          onClick={toggleExpand}
        />

        {/* Chart caption/label */}
        {chart.title && !isLoading && !hasError && (
          <p className="text-xs text-gray-500 dark:text-gray-400 mt-1 text-center italic">
            {chart.title}
          </p>
        )}
      </div>

      {/* Expanded modal view */}
      {isExpanded && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4"
          onClick={toggleExpand}
        >
          <div className="relative max-w-4xl max-h-[90vh] w-full">
            {/* Close button */}
            <button
              onClick={toggleExpand}
              className="absolute -top-10 right-0 text-white hover:text-gray-300 transition-colors"
              aria-label="Close expanded chart"
            >
              <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>

            {/* Expanded image */}
            <img
              src={imageSrc}
              alt={altText}
              className="w-full h-auto max-h-[85vh] object-contain rounded-lg shadow-2xl"
            />

            {/* Caption in modal */}
            {chart.title && (
              <p className="text-center text-white mt-3 text-sm">
                {chart.title}
              </p>
            )}
          </div>
        </div>
      )}
    </>
  );
}
